spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/kickoff?currentSchema=notification&TimeZone=UTC
    username: kickoff
    password: kickoff
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        default_schema: notification
  flyway:
    schemas: notification
    default-schema: notification
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8089

management:
  endpoints:
    web:
      exposure:
        include: health,info

kafka:
  topics:
    trade-status-changed: trade.status-changed
    coins-award: coins.award

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html