spring:
  data:
    redis:
      host: kickoff-redis.mkoudz.0001.euc1.cache.amazonaws.com
      port: 6379
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8084
              predicates:
                - Path=/api/v1/users/**

            - id: match-service
              uri: http://match-service:8081
              predicates:
                - Path=/api/v1/matches/**,/api/v1/players/**,/api/v1/games/**

            - id: prediction-service
              uri: http://prediction-service:8082
              predicates:
                - Path=/api/v1/predictions/**

            - id: coin-service
              uri: http://coin-service:8083
              predicates:
                - Path=/api/v1/coins/**

            - id: card-service
              uri: http://card-service:8085
              predicates:
                - Path=/api/v1/cards/**

            - id: pack-service
              uri: http://pack-service:8086
              predicates:
                - Path=/api/v1/packs/**

            - id: trade-service
              uri: http://trade-service:8087
              predicates:
                - Path=/api/v1/trades/**

            - id: fantasy-service
              uri: http://fantasy-service:8088
              predicates:
                - Path=/api/v1/fantasy/**

            - id: notification-service
              uri: http://notification-service:8089
              predicates:
                - Path=/api/v1/notifications/**