spring:
  application:
    name: prediction-service
  datasource:
    url: jdbc:postgresql://${RDS_ENDPOINT}/kickoff?currentSchema=prediction&TimeZone=UTC
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: prediction
    show-sql: false
  flyway:
    schemas: prediction
    default-schema: prediction
  kafka:
    bootstrap-servers: ${KAFKA_ENDPOINT}
    consumer:
      group-id: prediction-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.kickoff.prediction_service.event.MatchCompletedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  threads:
    virtual:
      enabled: true

server:
  port: 8082

match-service:
  url: http://match-service:8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

kafka:
  topics:
    match-results: match.results
    coins-award: coins.award

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html