spring:
  application:
    name: coin-service
  datasource:
    url: jdbc:postgresql://localhost:5432/kickoff?TimeZone=UTC
    username: kickoff
    password: kickoff
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: coin
    show-sql: false
  flyway:
    schemas: coin
    default-schema: coin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: coin-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.kickoff.coin_service.event.CoinsAwardedEvent

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info

kafka:
  topics:
    coins-award: coins.award

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html